version: '3'

volumes:
  prometheus_data: {}
  grafana-data: {}

services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 127.0.0.1:9090:9090
    depends_on: [4stats]

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana

  4stats:
    container_name: 4stats
    hostname: prometheusprometheus
    image: alx99/4stats:latest
    ports:
      - 8000:8000
