version: '3'

volumes:
  prometheus_data: {}

services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  yonsuu:
    container_name: yonsuu
    hostname: prometheusprometheus
    image: alx99/todo:latest
    ports:
      - 8000:8000
