version: 3

includes:
  common:
    taskfile: ./task/Taskfile.yml
    internal: true
    aliases:
      - c

tasks:
  clean:
    - rm -rf ./build
    - docker-compose down -v

  lint:
    cmds:
      - task: c:lint:go

  build:
    sources:
      - ./internal/**/*.go
      - ./cmd/**/*.go
      - ./go.mod
    generates:
      - ./build/4stats
    cmds:
      - CGO_ENABLED=0 go build -v -trimpath -ldflags "-s -w -X 'main.commitHash={{.COMMIT_HASH}}' -X 'main.compilationDate={{.DATE}}'" -o ./build/4stats ./cmd/4stats/main.go

  image:
    deps: [build]
    cmds:
      - task: c:docker:build
        vars:
          IMAGE_NAME: alx99/4stats:latest

  image-push:
    deps: [image]
    cmds:
      - docker push alx99/4stats:latest

  start:
    deps: [image]
    cmds:
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose stop
