version: 3

includes:
  common:
    taskfile: ./task/Taskfile.yml
    internal: true

tasks:
  clean:
    - rm -rf ./build
    - docker-compose down -v

  build:
    sources:
      - ./internal/**/*.go
      - ./cmd/**/*.go
      - ./go.mod
    generates:
      - ./build/yonsuu
    cmds:
      - CGO_ENABLED=0 go build -v -trimpath -ldflags "-s -w -X 'main.commitHash={{.COMMIT_HASH}}' -X 'main.compilationDate={{.DATE}}'" -o ./build/yonsuu ./cmd/yonsuu/main.go

  image:
    deps: [build]
    cmds:
      - task: common:docker-build
        vars:
          DOCKER_IMAGE: alx99/todo:latest

  start:
    deps: [image]
    cmds:
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose stop
