global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'yonsuu-metrics'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['yonsuu:8000']
