global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: '4stats-metrics'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['4stats:8000']
